### PR TITLE
Override QE app environment for versions 20.11.0 onwards.

### PR DESCRIPTION
**Pull request by csadorf**
Also remove prior releases.

### CODE REVIEW

**Comment by csadorf** [comment]
@yakutovicha No need to update the branch.

**Review by yakutovicha — APPROVED** [review]

**Comment by csadorf** [comment]
> @yakutovicha No need to update the branch.

@yakutovicha I see you still merged master. Were you not able to merge the PR otherwise?

**Comment by yakutovicha** [comment]
I don't remember exactly, but I guess the PR was automatically merged.

**Comment by csadorf** [comment]
> I don't remember exactly, but I guess the PR was automatically merged.

No, I meant you merged master into this branch. That should not have been necessary.

**Pull request merged**
