### PR TITLE
[DO NOT MERGE] add categories

### LINKED ISSUE #13: renaming groups
Here comes my proposal:

 - rename "groups" to "categories"
 - add a "categories.json" that contains "description" and "title" fields for each category
 - categories:
   - label: title/description
    - utilities: "Utilities" / Utility apps for everyday tasks
    - configuration: "Configuration" / Apps that configure your AiiDA lab setup.
    - quantum: "Quantum" / Apps that perform quantum-mechanical calculations.
    - classical: "Classical" / Apps that perform calculations based on classical force fields.

Of course, apps can be in more than one category.

@CasperWA @yakutovicha @giovannipizzi Let me know what you think today. 
I will then make the corresponding changes.

P.S. 'configuration' could also be called 'system' (both would be fine with me).

### PR DESCRIPTION
**Pull request by ltalirz**
fix #13 
 + rename groups to categories
 + rename categories
 + add categories to singlepage view5

### CODE REVIEW

**Comment by ltalirz** [comment]
I would like to add the categories to the front page as well but I suggest we wait until the other PRs are merged so that we really see how it would look like.

**Comment by yakutovicha** [comment]
please do not merge this PR until the Home app is modified accordingly.

**Comment by ltalirz** [comment]
@yakutovicha Alright.
By the way, let me know how you want to have the categories - I can easily add it at the top level of the `apps_meta.json` output of the app registry (currently only has one key "apps").
This way you don't have to deal with multiple files.

**Comment by yakutovicha** [comment]
> By the way, let me know how you want to have the categories - I can easily add it at the top level of the `apps_meta.json` output of the app registry

The `apps_meta.json` file generated by app-registry I don't really touch/need. The apps_meta.json which is used by the App Store is generated on AiiDA lab directly.

However, the question still remains: do we need to merge the information from `apps.json` and `categories.json`. Probably yes, if we need to pull this information by HTTP request - better to have a  single file. Having one HTTP request and one file that will be cached is better then two. I do not see an advantage in pulling two files.

**Comment by ltalirz** [comment]
> I do not see an advantage in pulling two files.

In getting the file there is no advantage, but it does make sense to keep the metadata of description and the metadata of apps separate (rather than putting both in one file and introducing an additional nesting in the json).

Combining 2 GET requests into 1 does not really matter when you have N times ... get requests for fetching metadata from every app.

**Comment by ltalirz** [comment]
@yakutovicha Should be ready for you to merge

**Comment by yakutovicha** [comment]
> @yakutovicha Should be ready for you to merge

Looks like you did the other way around: you removed  space symbols instead of 'Tab'. Could you please redo it? Just replace 'Tab' with 8 spaces.

Thanks

**Comment by yakutovicha** [comment]
thanks @ltalirz

**Pull request merged**
