### PR TITLE
(Temporarily) remove aiidalab-optimade

### PR DESCRIPTION
**Pull request by CasperWA**
~According to the "offline" determined system of how to report release sources, I have updated the `aiidalab-optimade` app's `git_url` value, specifying the branch to be used by default.~

Update: This PR will be changed to temporarily remove the `aiidalab-optimade` application. It will be reinstated once a repository re-factoring has happened.

### CODE REVIEW

**Comment by yakutovicha** [comment]
I think we should put it `on_hold` until the functionality is implemented in the AiiDA lab app store.

**Comment by CasperWA** [comment]
> I think we should put it `on_hold` until the functionality is implemented in the AiiDA lab app store.

Done.
Please put in a reference for the issue/PR when it's there.

**Comment by CasperWA** [comment]
Also, the CI tests fail, since the `git_url` is used to create the registry links to the application source code. So this should be updated accordingly.
I will not do this at this point, but later, when/if the implementation of this is ready in the AiiDA lab app store and "there is no way back".

**Comment by CasperWA** [comment]
This may become obsolete once the `aiidalab/aiidalab-optimade` repository has been split up according to off-GitHub agreements.

**Review by csadorf — APPROVED** [review]

**Pull request merged**
