### PR TITLE
aiidalab-home repo rename

### PR DESCRIPTION
**Pull request by unkcpz**

### CODE REVIEW

**Comment by unkcpz** [comment]
Wierd, it build find in my computer but here it fails with another issue.

**Comment by yakutovicha** [comment]
> Wierd, it build find in my computer but here it fails with another issue.

Yes, not sure what it means:
```python
packaging.version.InvalidVersion: Invalid version: 'stable'
```

**Comment by unkcpz** [comment]
Okay, found the issue. It was caused by the new version of package `packaging`, I pinned it to `<22` and it works. I can also reproduce the issue after updating the packaging to `22.0`. 
We still need to take a close look at it, I guess it might that `stable` is some sort "legacy version" label and removed from the packaging by https://github.com/pypa/packaging/pull/407.

**Comment by unkcpz** [comment]
@yakutovicha okay to merge this?

**Comment by unkcpz** [comment]
Open issue for `packaging` version at https://github.com/aiidalab/aiidalab-registry/issues/103

**Review by yakutovicha — APPROVED** [review]

**Comment by yakutovicha** [comment]
I let you merge this, @unkcpz

**Comment by danielhollas** [comment]
> Okay, found the issue. It was caused by the new version of package packaging, I pinned it to <22 and it works. I can also reproduce the issue after updating the packaging to 22.0.
We still need to take a close look at it, I guess it might that stable is some sort "legacy version" label and removed from the packaging by https://github.com/pypa/packaging/pull/407.

I discovered the the same issue in `aiidalab` repo https://github.com/aiidalab/aiidalab/issues/339

**Pull request merged**
